name: Run automation tests

on:
  push:
    branches:
      - master
      - meysam/dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - python-version: "3.8"
          tox-env: "py38"
        - python-version: "3.9"
          tox-env: "py39"
        - python-version: "3.10"
          tox-env: "py310"

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements-tests.txt
      
      - name: Run tests
        run: tox -e ${{ matrix.tox-env }}
